name: CI/CD

on:
  push:
    branches:
      - feature/*
      - fix/*
      - refactor/*
  pull_request:
    branches:
      - main
    types: 
    - opened
    - synchronize

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        yarn

    - name: Test code
      run: |
        yarn test

  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        yarn

    - name: Lint code
      run: |
        yarn lint

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        yarn

    - name: Build code
      run: |
        yarn build
